# Generated by Django 4.0.3 on 2022-08-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_client', models.DecimalField(decimal_places=0, max_digits=11)),
                ('mobile_operator_cod', models.PositiveSmallIntegerField()),
                ('timezone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('mes', models.CharField(max_length=200)),
                ('client', models.ManyToManyField(to='delivery.client')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start_sending', models.DateTimeField()),
                ('date_end_sending', models.DateTimeField()),
                ('message', models.ManyToManyField(to='delivery.message')),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.tag'),
        ),
    ]
