# Generated by Django 4.0.3 on 2022-08-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
